"""Changed Blog field from date to posted

Revision ID: 4b79a2036a75
Revises: 077d1a989464
Create Date: 2020-07-22 15:30:36.445488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b79a2036a75'
down_revision = '077d1a989464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('posted', sa.DateTime(), nullable=True))
    op.drop_column('blogs', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('date', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'posted')
    # ### end Alembic commands ###
