"""Second migration

Revision ID: ee1c8d003b8d
Revises: 4484a22bfb48
Create Date: 2020-07-23 12:22:17.811655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1c8d003b8d'
down_revision = '4484a22bfb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('tutorial_id', sa.Integer(), nullable=True))
    op.drop_column('comments', 'blog_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'tutorial_id')
    # ### end Alembic commands ###
